version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: build(deps)
      prefix-development: build(deps-dev)
    assignees:
      - davidwinter
