AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

require: rubocop-rspec

Layout/LineLength:
  Max: 120

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
